import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter, withComponentInputBinding } from '@angular/router';
import { 
  provideLucideIcons,
  LucideLayoutDashboard,
  LucideMessageCircleQuestion,
  LucideGamepad2,
  LucideClock,
  LucideHeartPulse,
  LucideMessageSquare,
  LucideCpu,
  LucideHardDrive,
  LucideTable,
  LucideTag,
  LucideMessageCircle,
  LucideVideo,
  LucideShoppingCart,
  LucideGraduationCap,
  LucideLibraryBig,
  LucideMegaphone,
  LucideDownloadCloud,
  LucideRocket,
  LucideWallet,
  LucideRepeat,
  LucideCircuitBoard,
  LucideLibrary,
  LucideMicroscope,
  LucideUsers,
  LucideBookOpen,
  LucideZap,
  LucideBell,
  LucideSettings,
  LucideShieldCheck,
  LucideLayers,
  LucideChevronDown,
  LucideChevronUp,
  LucideLogOut,
  LucideMenu,
  LucideSearch,
  LucidePlay,
  LucidePause,
  LucideVolumeX,
  LucideVolume2,
  LucideMaximize
} from '@lucide/angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes, withComponentInputBinding()),
    provideLucideIcons(
      LucideLayoutDashboard,
      LucideMessageCircleQuestion,
      LucideGamepad2,
      LucideClock,
      LucideHeartPulse,
      LucideMessageSquare,
      LucideCpu,
      LucideHardDrive,
      LucideTable,
      LucideTag,
      LucideMessageCircle,
      LucideVideo,
      LucideShoppingCart,
      LucideGraduationCap,
      LucideLibraryBig,
      LucideMegaphone,
      LucideDownloadCloud,
      LucideRocket,
      LucideWallet,
      LucideRepeat,
      LucideCircuitBoard,
      LucideLibrary,
      LucideMicroscope,
      LucideUsers,
      LucideBookOpen,
      LucideZap,
      LucideBell,
      LucideSettings,
      LucideShieldCheck,
      LucideLayers,
      LucideChevronDown,
      LucideChevronUp,
      LucideLogOut,
      LucideMenu,
      LucideSearch,
      LucidePlay,
      LucidePause,
      LucideVolumeX,
      LucideVolume2,
      LucideMaximize
    )
  ]
};
